name: NPC
author: onebone
version: 2.0
main: onebone\npc\Main
api:
- 3.0.0-ALPHA7
- 3.0.0-ALPHA8
- 3.0.0-ALPHA9
- 3.0.0-ALPHA10
- 3.0.0-ALPHA11
- 3.0.0-ALPHA12
- 3.0.0-ALPHA13
- 3.0.0-ALPHA14
- 3.0.0-ALPHA15

commands:
 npc:
  permission: npc.command.npc;npc.command.npc.create;npc.command.npc.remove;npc.command.npc.list;npc.command.npc.message;npc.command.npc.command;

permissions:
 npc:
  default: op
  children:
   npc.command:
    default: op
    children:
     npc.command.npc:
      default: op
      children:
       npc.command.npc.create:
        default: op
       npc.command.npc.remove:
        default: op
       npc.command.npc.list:
        default: op
       npc.command.npc.message:
        default: op
       npc.command.npc.command:
        default: op
       npc.command.npc.change:
        default: op
